[github]
# Register the app here: https://github.com/settings/applications/new
client_id = "37cdbb80c7733e2a1831"
client_secret = "75e648e981545902ab7802de94e2f2707c8e0ff8"

[azuread]
client_id = "3f7ee309-c0d2-4681-b06e-775ba87621aa"
client_secret = "V~-_VPM4i92VK5-FN5xA1~PTe0iqM.Rd9J"

[sqlalchemy]
database_url = "sqlite:///./quetz.sqlite"

[session]
# openssl rand -hex 32
secret = "b72376b88e6f249cb0921052ea8a092381ca17fd8bb0caf4d847e337b3d34cf8"
https_only = false

[logging]
level = "DEBUG"
file = "quetz.log"

[users]
admins = ["dummy:alice"]
